# Generated by Django 3.0.3 on 2020-05-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm_sam', '0002_auto_20200425_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
    ]
