# Generated by Django 3.1.5 on 2021-03-17 18:09

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rm_sam', '0003_remove_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='marked',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='present',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_first',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_last',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vacay_end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vacay_start_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessons',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='month',
            field=models.CharField(default='March', max_length=9),
        ),
        migrations.AddField(
            model_name='lesson',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first',
            field=models.CharField(default='first', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last',
            field=models.CharField(default='last', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='charge_rate',
            field=models.CharField(default='$120', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
